ip: 0.0.0.0
port: 9002

etcd:
  addr: 127.0.0.1:2379

redis:
  addr: 127.0.0.1:6379
  password:
  db:

kafka:
  addr:
  topic:
  group:

log:
  default: #默认日志配置，log.Debug("xxx")
    - writer: console                         #控制台标准输出 默认
      level: debug                            #标准输出日志的级别
    - writer: file                              #本地文件日志
      level: info                               #本地文件滚动日志的级别
      formatter: json                           #标准输出日志的格式
      writer_config: #本地文件输出具体配置
        filename: ./log/gate.log          #本地文件滚动日志存放的路径
        roll_type: size                         #文件滚动类型,size为按大小滚动
        max_age: 7                              #最大日志保留天数
        max_size: 10                            #本地文件滚动日志的大小 单位 MB
        max_backups: 10                         #最大日志文件数
        compress: false                        #日志文件是否压缩